### ISSUE TITLE
cc cv

### ISSUE THREAD

**Issue by Hawkishx** [Inplex-sys/Hawkish-Eyes-NoDualHook#1]
cc cv? c'est Hawkishx je sais que tu vois mes issues! 
je viens te voir pour te dire que tu as commises une erreur, le repo que tu viens de cloner et sous license MIT format professionnel la description du code de mon readme décris EXACTEMENT ce que fais le code!
 tu dois donc le supprimer sinon je porterais plainte pour vole de code et diffamation!
Tu remarqueras tout de même que la personne avec qui tu t'es ""embrouillé"" n'est plus dans la team!  
bonne journée a toi, je te laisse un petit délais avant de demander une restriction de ton contenu !

**Comment by Pasha-malware** [comment]
why do you dualhook ur malware in the first place, now you mad that you got exposed lol

**Comment by Hawkishx** [comment]
Si avec blackface/hisslot en vocal :)
libre et open source sous réserve des termes d'utilisations du propriétaire et je n'autorise aucune copie modifié de hawkish donc s'il te plait je te le demande calmement et avec toute la politesse qui t'es dû.
Peux tu mettre ton repo en privé?

**Comment by detectedent** [comment]
its a ratter
why u posting malaware

**Comment by Hawkishx** [comment]
all is explain on my readme!

**Comment by Simpili** [comment]
I reported the repo and it got banned, doing gods work :)

**Comment by Inplex-sys** [comment]
> I reported the repo and it got banned, doing gods work :)

i did too
![image](https://github.com/Inplex-sys/Hawkish-Eyes-NoDualHook/assets/69421356/70d2806c-dd5c-4c93-9cf2-1d7ef7790d0e)

**Comment by Inplex-sys** [comment]
> cc cv? c'est Hawkishx je sais que tu vois mes issues! je viens te voir pour te dire que tu as commises une erreur, le repo que tu viens de cloner et sous license MIT format professionnel la description du code de mon readme décris EXACTEMENT ce que fais le code! tu dois donc le supprimer sinon je porterais plainte pour vole de code et diffamation! Tu remarqueras tout de même que la personne avec qui tu t'es ""embrouillé"" n'est plus dans la team! bonne journée a toi, je te laisse un petit délais avant de demander une restriction de ton contenu !

T'as perdu, encore ...

**Comment by Hawkishx** [comment]
tant pis on reviendra plus fort et pis j'ai déjà préparer de quoi contre attaquer, mais pas sur que tu puisses faire quelque chose... :)

**Comment by Inplex-sys** [comment]
Ca fait 4 mois que vous répétez la même chose, et vous êtes toujours dans la menace, faut changer de discours

**Comment by Simpili** [comment]
> tant pis on reviendra plus fort et pis j'ai déjà préparer de quoi contre attaquer, mais pas sur que tu puisses faire quelque chose... :)

what is bro cooking, no matter what I will still report his repo

**Comment by Simpili** [comment]
> tant pis on reviendra plus fort et pis j'ai déjà préparer de quoi contre attaquer, mais pas sur que tu puisses faire quelque chose... :)

Why did you take ur webpanel offline?

**Comment by Hawkishx** [comment]
je ne menace personne bg, je te previens et mon web panel est offline pour que github remette mon repo en publique :(((

**Comment by Hawkishx** [comment]
ils ont accepté de me remettre en publique sous cette condition
