### ISSUE TITLE
Imagine if this is duel hooked 

### ISSUE THREAD

**Issue by biglines** [Inplex-sys/Hawkish-Eyes-NoDualHook#10]

**Comment by DARKNOSY** [comment]
lmfao would be funny

**Comment by Inplex-sys** [comment]
Yes, but unfortunately it's not

**Comment by 9pings** [comment]
do u man have a discord server for this shit?

**Comment by 9pings** [comment]
i think ive seen something like this before, but with a diffrent name yk

**Comment by Inplex-sys** [comment]
yes it was named blackcap grabber

**Comment by 9pings** [comment]
it wasnt even working, and this doesnt work took, some guy opened the file but i got nothing
