### ISSUE TITLE
I cant find the built file

### ISSUE THREAD

**Issue by 9pings** [Inplex-sys/Hawkish-Eyes-NoDualHook#11]
Where can i find it

**Comment by Inplex-sys** [comment]
`builder.py`

**Comment by 9pings** [comment]
nah ive deleted that shit but ty

**Comment by Inplex-sys** [comment]
yes this shit tbh, i just removed the dual hook

**Comment by 9pings** [comment]
is not even sending shit yk

**Comment by Inplex-sys** [comment]
the repo is discontinued, maybe discord did a lil update
