### ISSUE TITLE
What does this mean? I have python?

### ISSUE THREAD

**Issue by zzlyz** [Inplex-sys/Hawkish-Eyes-NoDualHook#13]
I ran install.bat, it worked and then i ran start.bat and this appeared.
![image](https://github.com/Inplex-sys/Hawkish-Eyes-NoDualHook/assets/84344494/e5f7bfc1-0d6b-409f-9117-771216bf5c94)
How can i fix this?

**Comment by zzlyz** [comment]
Btw when i press any key to continue it just closes :/

**Comment by ChickenWithACrown** [comment]
try redownloading it
